version: "3.9"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.14.1"
    environment:
    - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    user: root
  appsearch:
    image: "searchboost:appsearch"
    ports:
      - "3002:3002"
    environment:
    - elasticsearch.host='http://host.docker.internal:9200'
    - allow_es_settings_modification=true
    - app_search.engine.document_size.limit='1024kb'
    - secret_management.encryption_keys=[4a2cd3f81d39bf28738c10db0ca782095ffac07279561809eecc722e0c20eb09]
    extra_hosts:
    - "host.docker.internal:host-gateway"
  ai_server:
    image: "searchboost:ai_server"
    ports:
      - "5000:5000"
  react_frontend:
    image: "searchboost:react_frontend_t"
    ports:
      - "3000:80"